name: CI for folder1

on:
  push:
    branches:
      - main
    paths: 
      - 'folder1/**' 

  pull_request:
    branches:
      - main 
    paths: 
      - 'folder1/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./folder1
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: |
          python3 --version
          node --version
          docker --version
          ls -lah
          cat file.txt
      - name: Git commit test
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "This is a test " >> file.txt
          git add .
          git commit -m "Update files for version"
          git push origin "${{ env.CURRENT_VERSION }}"