name: CI for folder1

on:
  push:
    branches:
      - main
    paths: 
      - 'folder1/**' 

  pull_request:
    branches:
      - main 
    paths: 
      - 'folder1/**' 

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./folder1
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check Python, Node.js, and Docker versions
        run: |
          python3 --version
          node --version
          docker --version
          ls -lah
          cat file.txt

      - name: Git commit test
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          echo "This is a test " >> file.txt
          git add .
          git commit -m "Update files for version"
          git push -u origin "main"

      - name: Use github secrets
        run: |
          echo "Using GitHub secrets"
          echo "${{ secrets.MUTANT_CAR }}" > secret.txt
          cat secret.txt